name: validate-json
on:
  pull_request:
  workflow_dispatch:

jobs:
  validate-json:
    name: Validate JSON
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Profiles
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: /schema/profiles.schema.json
          jsons: /data/profiles.json
