name: validate-json
on:
  pull_request:
  workflow_dispatch:

jobs:
  validate-json:
    name: Validate JSON
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate Profiles
        uses: snapcart/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json_schema: ./schemas/profiles.schema.json
          json_path_pattern: ./data/profiles.json
          send_comment: true
          clear_comments: true
